import React from 'react'
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import { ScrollArea } from "@/components/ui/scroll-area"

interface City {
  name: string
  rank: number
}

const ALASKA_CITIES: City[] = [
  { rank: 1, name: "Anchorage" },
  { rank: 2, name: "Fairbanks" },
  { rank: 3, name: "Juneau" },
  { rank: 4, name: "Knik-Fairview" },
  { rank: 5, name: "Badger" },
  { rank: 6, name: "College" },
  { rank: 7, name: "North Lakes" },
  { rank: 8, name: "Wasilla" },
  { rank: 9, name: "Tanaina" },
  { rank: 10, name: "Meadow Lakes" },
  { rank: 11, name: "Kalifornsky" },
  { rank: 12, name: "Sitka" },
  { rank: 13, name: "Ketchikan" },
  { rank: 14, name: "Kenai" },
  { rank: 15, name: "South Lakes" },
  { rank: 16, name: "Palmer" },
  { rank: 17, name: "Steele Creek" },
  { rank: 18, name: "Sterling" },
  { rank: 19, name: "Gateway" },
  { rank: 20, name: "Bethel" },
  { rank: 21, name: "Homer" },
  { rank: 22, name: "Kodiak" },
  { rank: 23, name: "Chena Ridge" },
  { rank: 24, name: "Fishhook" },
  { rank: 25, name: "Soldotna" },
  { rank: 26, name: "Utqiaġvik" },
  { rank: 27, name: "Nikiski" },
  { rank: 28, name: "Mill Bay" },
  { rank: 29, name: "Unalaska" },
  { rank: 30, name: "Farmers Loop" },
  { rank: 31, name: "Petersburg" },
  { rank: 32, name: "Butte" },
  { rank: 33, name: "Valdez" },
  { rank: 34, name: "Nome" },
  { rank: 35, name: "Big Lake" },
  { rank: 36, name: "Eielson AFB" },
  { rank: 37, name: "Ester" },
  { rank: 38, name: "Kotzebue" },
  { rank: 39, name: "Ridgeway" },
  { rank: 40, name: "Farm Loop" },
  { rank: 41, name: "Seward" },
  { rank: 42, name: "Goldstream" },
  { rank: 43, name: "North Pole" },
  { rank: 44, name: "Cordova" },
  { rank: 45, name: "Anchor Point" },
  { rank: 46, name: "Kodiak Station" },
  { rank: 47, name: "Houston" },
  { rank: 48, name: "Fritz Creek" },
  { rank: 49, name: "Dillingham" },
  { rank: 50, name: "Wrangell" },
  { rank: 51, name: "Deltana" },
  { rank: 52, name: "Prudhoe Bay" },
  { rank: 53, name: "Willow" },
  { rank: 54, name: "Point MacKenzie" },
  { rank: 55, name: "Haines" },
  { rank: 56, name: "Lazy Mountain" },
  { rank: 57, name: "Susitna North" },
  { rank: 58, name: "Akutan" },
  { rank: 59, name: "Cohoe" },
  { rank: 60, name: "Metlakatla" },
  { rank: 61, name: "Diamond Ridge" },
  { rank: 62, name: "Tok" },
  { rank: 63, name: "Sutton-Alpine" },
  { rank: 64, name: "Hooper Bay" },
  { rank: 65, name: "Salamatof" },
  { rank: 66, name: "Skagway" },
  { rank: 67, name: "Bear Creek" },
  { rank: 68, name: "Womens Bay" },
  { rank: 69, name: "Funny River" },
  { rank: 70, name: "Talkeetna" },
  { rank: 71, name: "Craig" },
  { rank: 72, name: "Ninilchik" },
  { rank: 73, name: "Buffalo Soapstone" },
  { rank: 74, name: "Delta Junction" },
  { rank: 75, name: "Denali Park" },
  { rank: 76, name: "Hoonah" },
  { rank: 77, name: "Chevak" },
  { rank: 78, name: "Tuntutuliak" },
  { rank: 79, name: "Healy" },
  { rank: 80, name: "Knik River" },
  { rank: 81, name: "Savoonga" },
  { rank: 82, name: "King Cove" },
  { rank: 83, name: "Emmonak" },
  { rank: 84, name: "Happy Valley" },
  { rank: 85, name: "Kwethluk" },
  { rank: 86, name: "Point Hope" },
  { rank: 87, name: "Togiak" },
  { rank: 88, name: "Quinhagak" },
  { rank: 89, name: "Selawik" },
  { rank: 90, name: "Unalakleet" },
  { rank: 91, name: "Fox River" },
  { rank: 92, name: "Alakanuk" },
  { rank: 93, name: "Klawock" },
  { rank: 94, name: "Kwigillingok" },
  { rank: 95, name: "Toksook Bay" },
  { rank: 96, name: "Noorvik" },
  { rank: 97, name: "Salcha" },
  { rank: 98, name: "Kotlik" },
  { rank: 99, name: "Gambell" },
  { rank: 100, name: "Pleasant Valley" },
  { rank: 101, name: "Sand Point" },
  { rank: 102, name: "Stebbins" },
  { rank: 103, name: "Gustavus" },
  { rank: 104, name: "Kachemak" },
  { rank: 105, name: "Mountain Village" },
  { rank: 106, name: "Pilot Station" },
  { rank: 107, name: "Wainwright" },
  { rank: 108, name: "Nunapitchuk" },
  { rank: 109, name: "Scammon Bay" },
  { rank: 110, name: "St. Mary's" },
  { rank: 111, name: "Kipnuk" },
  { rank: 112, name: "Moose Creek" },
  { rank: 113, name: "Shishmaref" },
  { rank: 114, name: "Yakutat" },
  { rank: 115, name: "Noatak" },
  { rank: 116, name: "Big Delta" },
  { rank: 117, name: "Kake" },
  { rank: 118, name: "Glennallen" },
  { rank: 119, name: "Buckland" },
  { rank: 120, name: "Aniak" },
  { rank: 121, name: "Napaskiak" },
  { rank: 122, name: "Chefornak" },
  { rank: 123, name: "New Stuyahok" },
  { rank: 124, name: "Nuiqsut" },
  { rank: 125, name: "Tuluksak" },
  { rank: 126, name: "Tununak" },
  { rank: 127, name: "Thorne Bay" },
  { rank: 128, name: "South Van Horn" },
  { rank: 129, name: "Marshall" },
  { rank: 130, name: "Tazlina" },
  { rank: 131, name: "Manokotak" },
  { rank: 132, name: "Galena" },
  { rank: 133, name: "Akiak" },
  { rank: 134, name: "St. Michael" },
  { rank: 135, name: "Kiana" },
  { rank: 136, name: "Brevig Mission" },
  { rank: 137, name: "Kivalina" },
  { rank: 138, name: "Fort Yukon" },
  { rank: 139, name: "False Pass" },
  { rank: 140, name: "Russian Mission" },
  { rank: 141, name: "Naknek" },
  { rank: 142, name: "Anaktuvuk Pass" },
  { rank: 143, name: "St. Paul" },
  { rank: 144, name: "Eek" },
  { rank: 145, name: "King Salmon" },
  { rank: 146, name: "Akiachak" },
  { rank: 147, name: "Saxman" },
  { rank: 148, name: "Two Rivers" },
  { rank: 149, name: "Hydaburg" },
  { rank: 150, name: "Kasigluk" },
  { rank: 151, name: "Elim" },
  { rank: 152, name: "Napakiak" },
  { rank: 153, name: "Kongiganak" },
  { rank: 154, name: "Nenana" },
  { rank: 155, name: "Copper Center" },
  { rank: 156, name: "Angoon" },
  { rank: 157, name: "Coldfoot" },
  { rank: 158, name: "Clam Gulch" },
  { rank: 159, name: "Northway" },
  { rank: 160, name: "Koyuk" },
  { rank: 161, name: "Huslia" },
  { rank: 162, name: "Nightmute" },
  { rank: 163, name: "Tyonek" },
  { rank: 164, name: "Chickaloon" },
  { rank: 165, name: "Harding-Birch Lakes" },
  { rank: 166, name: "McGrath" },
  { rank: 167, name: "Trapper Creek" },
  { rank: 168, name: "Kaktovik" },
  { rank: 169, name: "Lower Kalskag" },
  { rank: 170, name: "Pitkas Point" },
  { rank: 171, name: "Whittier" },
  { rank: 172, name: "Seldovia" },
  { rank: 173, name: "Atqasuk" },
  { rank: 174, name: "Goodnews Bay" },
  { rank: 175, name: "Ambler" },
  { rank: 176, name: "Shungnak" },
  { rank: 177, name: "Halibut Cove" },
  { rank: 178, name: "Koliganek" },
  { rank: 179, name: "Dry Creek" },
  { rank: 180, name: "Teller" },
  { rank: 181, name: "Kasilof" },
  { rank: 182, name: "Tanana" },
  { rank: 183, name: "Nulato" },
  { rank: 184, name: "Seldovia Village" },
  { rank: 185, name: "Cooper Landing" },
  { rank: 186, name: "Glacier View" },
  { rank: 187, name: "Tetlin" },
  { rank: 188, name: "Alcan Border" },
  { rank: 189, name: "Arctic Village" },
  { rank: 190, name: "Nunam Iqua" },
  { rank: 191, name: "Upper Kalskag" },
  { rank: 192, name: "Shaktoolik" },
  { rank: 193, name: "Old Harbor" },
  { rank: 194, name: "Kenny Lake" },
  { rank: 195, name: "Mekoryuk" },
  { rank: 196, name: "Grayling" },
  { rank: 197, name: "Aleknagik" },
  { rank: 198, name: "Moose Pass" },
  { rank: 199, name: "Eareckson Station" },
  { rank: 200, name: "Nikolaevsk" },
  { rank: 201, name: "White Mountain" },
  { rank: 202, name: "Mentasta Lake" },
  { rank: 203, name: "Anderson" },
  { rank: 204, name: "Kobuk" },
  { rank: 205, name: "Point Lay" },
  { rank: 206, name: "Allakaket" },
  { rank: 207, name: "Holy Cross" },
  { rank: 208, name: "Deering" },
  { rank: 209, name: "Golovin" },
  { rank: 210, name: "Port Lions" },
  { rank: 211, name: "Wales" },
  { rank: 212, name: "Fox" },
  { rank: 213, name: "Nanwalek" },
  { rank: 214, name: "Nelchina" },
  { rank: 215, name: "Port Alsworth" },
  { rank: 216, name: "Kaltag" },
  { rank: 217, name: "Adak" },
  { rank: 218, name: "Newhalen" },
  { rank: 219, name: "Gakona" },
  { rank: 220, name: "Hollis" },
  { rank: 221, name: "Port Graham" },
  { rank: 222, name: "Tanacross" },
  { rank: 223, name: "Ruby" },
  { rank: 224, name: "Mosquito Lake" },
  { rank: 225, name: "Coffman Cove" },
  { rank: 226, name: "Hope" },
  { rank: 227, name: "Central" },
  { rank: 228, name: "Naukati Bay" },
  { rank: 229, name: "Nondalton" },
  { rank: 230, name: "Willow Creek" },
  { rank: 231, name: "Chalkyitsik" },
  { rank: 232, name: "Nelson Lagoon" },
  { rank: 233, name: "Tenakee Springs" },
  { rank: 234, name: "Kokhanok" },
  { rank: 235, name: "Silver Springs" },
  { rank: 236, name: "Mendeltna" },
  { rank: 237, name: "Oscarville" },
  { rank: 238, name: "Beaver" },
  { rank: 239, name: "Ekwok" },
  { rank: 240, name: "Cantwell" },
  { rank: 241, name: "Ouzinkie" },
  { rank: 242, name: "Venetie" },
  { rank: 243, name: "Chuathbaluk" },
  { rank: 244, name: "Primrose" },
  { rank: 245, name: "Minto" },
  { rank: 246, name: "Shageluk" },
  { rank: 247, name: "Fort Greely" },
  { rank: 248, name: "Koyukuk" },
  { rank: 249, name: "Pelican" },
  { rank: 250, name: "Port Heiden" },
  { rank: 251, name: "Eagle" },
  { rank: 252, name: "Nikolai" },
  { rank: 253, name: "Sleetmute" },
  { rank: 254, name: "Whale Pass" },
  { rank: 255, name: "Chignik" },
  { rank: 256, name: "Hughes" },
  { rank: 257, name: "Igiugig" },
  { rank: 258, name: "Perryville" },
  { rank: 259, name: "Diomede" },
  { rank: 260, name: "Eagle Village" },
  { rank: 261, name: "Klukwan" },
  { rank: 262, name: "Skwentna" },
  { rank: 263, name: "Crown Point" },
  { rank: 264, name: "Excursion Inlet" },
  { rank: 265, name: "Port Alexander" },
  { rank: 266, name: "Anvik" },
  { rank: 267, name: "Slana" },
  { rank: 268, name: "Chenega" },
  { rank: 269, name: "Takotna" },
  { rank: 270, name: "Akhiok" },
  { rank: 271, name: "Chitina" },
  { rank: 272, name: "Clark's Point" },
  { rank: 273, name: "South Naknek" },
  { rank: 274, name: "Twin Hills" },
  { rank: 275, name: "Gulkana" },
  { rank: 276, name: "St. George" },
  { rank: 277, name: "Pilot Point" },
  { rank: 278, name: "Atka" },
  { rank: 279, name: "Newtok" },
  { rank: 280, name: "Platinum" },
  { rank: 281, name: "Chistochina" },
  { rank: 282, name: "Cold Bay" },
  { rank: 283, name: "Rampart" },
  { rank: 284, name: "Stony River" },
  { rank: 285, name: "Port Clarence" },
  { rank: 286, name: "Tatitlek" },
  { rank: 287, name: "Chignik Lagoon" },
  { rank: 288, name: "Petersville" },
  { rank: 289, name: "Whitestone" },
  { rank: 290, name: "Alatna" },
  { rank: 291, name: "Mud Bay" },
  { rank: 292, name: "Chignik Lake" },
  { rank: 293, name: "Circle" },
  { rank: 294, name: "Tolsona" },
  { rank: 295, name: "Egegik" },
  { rank: 296, name: "Levelock" },
  { rank: 297, name: "Evansville" },
  { rank: 298, name: "Karluk" },
  { rank: 299, name: "Larsen Bay" },
  { rank: 300, name: "Chase" },
  { rank: 301, name: "Ferry" },
  { rank: 302, name: "Healy Lake" },
  { rank: 303, name: "Kasaan" },
  { rank: 304, name: "Covenant Life" },
  { rank: 305, name: "Edna Bay" },
  { rank: 306, name: "Bettles" },
  { rank: 307, name: "Wiseman" },
  { rank: 308, name: "Attu Station" },
  { rank: 309, name: "Manley Hot Springs" },
  { rank: 310, name: "Elfin Cove" },
  { rank: 311, name: "Hyder" },
  { rank: 312, name: "Kupreanof" },
  { rank: 313, name: "Tonsina" },
  { rank: 314, name: "Lake Minchumina" },
  { rank: 315, name: "Port Protection" },
  { rank: 316, name: "Sunrise" },
  { rank: 317, name: "Crooked Creek" },
  { rank: 318, name: "Livengood" },
  { rank: 319, name: "Pedro Bay" },
  { rank: 320, name: "Iliamna" },
  { rank: 321, name: "Lutak" },
  { rank: 322, name: "Nikolski" },
  { rank: 323, name: "Lime Village" },
  { rank: 324, name: "Stevens Village" },
  { rank: 325, name: "Red Devil" },
  { rank: 326, name: "Four Mile Road" },
  { rank: 327, name: "Beluga" },
  { rank: 328, name: "Birch Creek" },
  { rank: 329, name: "Portage Creek" },
  { rank: 330, name: "McCarthy" }
]

interface AlaskaCitySelectorProps {
  onCitySelect: (city: City) => void
  selectedCities: string[]
}

const AlaskaCitySelector: React.FC<AlaskaCitySelectorProps> = ({ onCitySelect, selectedCities }) => {
  return (
    <div className="space-y-2">
      <label htmlFor="city-select" className="block text-sm font-medium text-[#E4B649]">
        Select an Alaska City
      </label>
      <Select onValueChange={(value) => {
        const selectedCity = ALASKA_CITIES.find(city => city.name === value)
        if (selectedCity) onCitySelect(selectedCity)
      }}>
        <SelectTrigger id="city-select" className="w-full bg-black/50 border-[#E4B649]/20 text-white">
          <SelectValue placeholder="Choose a city" />
        </SelectTrigger>
        <SelectContent className="bg-black border-[#E4B649]/20">
          <ScrollArea className="h-[200px]">
            {ALASKA_CITIES.map((city) => (
              <SelectItem 
                key={city.rank} 
                value={city.name}
                className="text-white hover:bg-[#E4B649]/20"
                disabled={selectedCities.includes(city.name)}
              >
                {city.name}
              </SelectItem>
            ))}
          </ScrollArea>
        </SelectContent>
      </Select>
      <p className="text-xs text-[#E4B649]/70">
        * You can select up to 10 cities from Alaska
      </p>
    </div>
  )
}

export default AlaskaCitySelector

