import React from 'react'
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import { ScrollArea } from "@/components/ui/scroll-area"

interface City {
  name: string
  rank: number
}

const ARIZONA_CITIES: City[] = [
  { rank: 1, name: "Phoenix" },
  { rank: 2, name: "Tucson" },
  { rank: 3, name: "Mesa" },
  { rank: 4, name: "Chandler" },
  { rank: 5, name: "Gilbert" },
  { rank: 6, name: "Glendale" },
  { rank: 7, name: "Scottsdale" },
  { rank: 8, name: "Peoria" },
  { rank: 9, name: "Tempe" },
  { rank: 10, name: "Surprise" },
  { rank: 11, name: "Goodyear" },
  { rank: 12, name: "Buckeye" },
  { rank: 13, name: "San Tan Valley" },
  { rank: 14, name: "Yuma" },
  { rank: 15, name: "Avondale" },
  { rank: 16, name: "Queen Creek" },
  { rank: 17, name: "Flagstaff" },
  { rank: 18, name: "Maricopa" },
  { rank: 19, name: "Casas Adobes" },
  { rank: 20, name: "Casa Grande" },
  { rank: 21, name: "Marana" },
  { rank: 22, name: "Lake Havasu City" },
  { rank: 23, name: "Prescott Valley" },
  { rank: 24, name: "Catalina Foothills" },
  { rank: 25, name: "Oro Valley" },
  { rank: 26, name: "Prescott" },
  { rank: 27, name: "Sierra Vista" },
  { rank: 28, name: "Bullhead City" },
  { rank: 29, name: "Apache Junction" },
  { rank: 30, name: "San Luis" },
  { rank: 31, name: "Sun City" },
  { rank: 32, name: "Sahuarita" },
  { rank: 33, name: "Kingman" },
  { rank: 34, name: "El Mirage" },
  { rank: 35, name: "Drexel Heights" },
  { rank: 36, name: "Fortuna Foothills" },
  { rank: 37, name: "Sun City West" },
  { rank: 38, name: "Fountain Hills" },
  { rank: 39, name: "Florence" },
  { rank: 40, name: "Anthem" },
  { rank: 41, name: "Rio Rico" },
  { rank: 42, name: "Green Valley" },
  { rank: 43, name: "Coolidge" },
  { rank: 44, name: "Nogales" },
  { rank: 45, name: "Eloy" },
  { rank: 46, name: "New River" },
  { rank: 47, name: "Flowing Wells" },
  { rank: 48, name: "Payson" },
  { rank: 49, name: "Fort Mohave" },
  { rank: 50, name: "Vail" },
  { rank: 51, name: "Douglas" },
  { rank: 52, name: "Somerton" },
  { rank: 53, name: "Tanque Verde" },
  { rank: 54, name: "Valencia West" },
  { rank: 55, name: "Sierra Vista Southeast" },
  { rank: 56, name: "Sun Lakes" },
  { rank: 57, name: "Chino Valley" },
  { rank: 58, name: "Gold Canyon" },
  { rank: 59, name: "New Kingman-Butler" },
  { rank: 60, name: "Cottonwood" },
  { rank: 61, name: "Tucson Mountains" },
  { rank: 62, name: "Tucson Estates" },
  { rank: 63, name: "Camp Verde" },
  { rank: 64, name: "Paradise Valley" },
  { rank: 65, name: "Saddlebrooke" },
  { rank: 66, name: "Show Low" },
  { rank: 67, name: "Verde Village" },
  { rank: 68, name: "Safford" },
  { rank: 69, name: "Sedona" },
  { rank: 70, name: "Corona Tucson" },
  { rank: 71, name: "Picture Rocks" },
  { rank: 72, name: "Winslow" },
  { rank: 73, name: "Tuba City" },
  { rank: 74, name: "Wickenburg" },
  { rank: 75, name: "Arizona City" },
  { rank: 76, name: "Golden Valley" },
  { rank: 77, name: "Page" },
  { rank: 78, name: "Globe" },
  { rank: 79, name: "Tolleson" },
  { rank: 80, name: "Litchfield Park" },
  { rank: 81, name: "Youngtown" },
  { rank: 82, name: "Snowflake" },
  { rank: 83, name: "Avra Valley" },
  { rank: 84, name: "Catalina" },
  { rank: 85, name: "Williamson" },
  { rank: 86, name: "Village Oak Creek (Big Park)" },
  { rank: 87, name: "Citrus Park" },
  { rank: 88, name: "Rincon Valley" },
  { rank: 89, name: "Thatcher" },
  { rank: 90, name: "Kayenta" },
  { rank: 91, name: "Benson" },
  { rank: 92, name: "Cave Creek" },
  { rank: 93, name: "Guadalupe" },
  { rank: 94, name: "Clarkdale" },
  { rank: 95, name: "Three Points" },
  { rank: 96, name: "Bisbee" },
  { rank: 97, name: "Doney Park" },
  { rank: 98, name: "Summit" },
  { rank: 99, name: "Holbrook" },
  { rank: 100, name: "Dewey-Humboldt" },
  { rank: 101, name: "Lake Montezuma" },
  { rank: 102, name: "South Tucson" },
  { rank: 103, name: "San Carlos" },
  { rank: 104, name: "Eagar" },
  { rank: 105, name: "Paulden" },
  { rank: 106, name: "Taylor" },
  { rank: 107, name: "Whiteriver" },
  { rank: 108, name: "Pinetop-Lakeside" },
  { rank: 109, name: "Avenue B C" },
  { rank: 110, name: "Chinle" },
  { rank: 111, name: "Clifton" },
  { rank: 112, name: "Red Rock Pinal County" },
  { rank: 113, name: "Cornville" },
  { rank: 114, name: "Carefree" },
  { rank: 115, name: "Williams" },
  { rank: 116, name: "San Manuel" },
  { rank: 117, name: "Fort Defiance" },
  { rank: 118, name: "Cordes Lakes" },
  { rank: 119, name: "Parker" },
  { rank: 120, name: "St. Johns" },
  { rank: 121, name: "Lake Woods" },
  { rank: 122, name: "Willcox" },
  { rank: 123, name: "Whetstone" },
  { rank: 124, name: "Timberline-Fernwood" },
  { rank: 125, name: "Kachina Village" },
  { rank: 126, name: "Pima" },
  { rank: 127, name: "Oracle" },
  { rank: 128, name: "White Mountain Lake" },
  { rank: 129, name: "Swift Trail Junction" },
  { rank: 130, name: "Ajo" },
  { rank: 131, name: "Colorado City" },
  { rank: 132, name: "Valle Vista" },
  { rank: 133, name: "Bagdad" },
  { rank: 134, name: "Mohave Valley" },
  { rank: 135, name: "Sacaton" },
  { rank: 136, name: "Desert Hills" },
  { rank: 137, name: "Wellton" },
  { rank: 138, name: "Heber-Overgaard" },
  { rank: 139, name: "Superior" },
  { rank: 140, name: "Star Valley" },
  { rank: 141, name: "Rio Verde" },
  { rank: 142, name: "Linden" },
  { rank: 143, name: "Sells" },
  { rank: 144, name: "Quartzsite" },
  { rank: 145, name: "Central Heights-Midland City" },
  { rank: 146, name: "Black Canyon City" },
  { rank: 147, name: "Blackwater" },
  { rank: 148, name: "Joseph City" },
  { rank: 149, name: "Beaver Dam" },
  { rank: 150, name: "Window Rock" },
  { rank: 151, name: "Grand Canyon Village" },
  { rank: 152, name: "Fort Valley" },
  { rank: 153, name: "Kaibab Estates West" },
  { rank: 154, name: "Scenic" },
  { rank: 155, name: "Kearny" },
  { rank: 156, name: "Gila Bend" },
  { rank: 157, name: "Pinetop Country Club" },
  { rank: 158, name: "Kaibito" },
  { rank: 159, name: "Red Lake" },
  { rank: 160, name: "North Fork" },
  { rank: 161, name: "Springerville" },
  { rank: 162, name: "Mountain View Ranches" },
  { rank: 163, name: "Lukachukai" },
  { rank: 164, name: "Meadview" },
  { rank: 165, name: "Canyon Day" },
  { rank: 166, name: "Huachuca City" },
  { rank: 167, name: "Spring Valley" },
  { rank: 168, name: "Peach Springs" },
  { rank: 169, name: "Miami" },
  { rank: 170, name: "Centennial Park" },
  { rank: 171, name: "Tsaile" },
  { rank: 172, name: "Bellemont" },
  { rank: 173, name: "Bylas" },
  { rank: 174, name: "Peridot" },
  { rank: 175, name: "Morenci" },
  { rank: 176, name: "LeChee" },
  { rank: 177, name: "Pine" },
  { rank: 178, name: "Pirtleville" },
  { rank: 179, name: "Second Mesa" },
  { rank: 180, name: "First Mesa" },
  { rank: 181, name: "Congress" },
  { rank: 182, name: "Mescal" },
  { rank: 183, name: "Tubac" },
  { rank: 184, name: "Cienega Springs" },
  { rank: 185, name: "Parks" },
  { rank: 186, name: "Six Shooter Canyon" },
  { rank: 187, name: "Tonto Basin" },
  { rank: 188, name: "Cibecue" },
  { rank: 189, name: "Wagon Wheel" },
  { rank: 190, name: "Dilkon" },
  { rank: 191, name: "Tombstone" },
  { rank: 192, name: "Fredonia" },
  { rank: 193, name: "Dolan Springs" },
  { rank: 194, name: "Mesa Caballo" },
  { rank: 195, name: "Blue Ridge" },
  { rank: 196, name: "St. David" },
  { rank: 197, name: "Ak-Chin Village" },
  { rank: 198, name: "Leupp" },
  { rank: 199, name: "Naco" },
  { rank: 200, name: "Claypool" },
  { rank: 201, name: "Shongopovi" },
  { rank: 202, name: "Cactus Flats" },
  { rank: 203, name: "Mammoth" },
  { rank: 204, name: "Casa Blanca" },
  { rank: 205, name: "Seven Mile" },
  { rank: 206, name: "Moenkopi" },
  { rank: 207, name: "McNary" },
  { rank: 208, name: "Pinon" },
  { rank: 209, name: "Wilhoit" },
  { rank: 210, name: "Bouse" },
  { rank: 211, name: "Gila Crossing" },
  { rank: 212, name: "Strawberry" },
  { rank: 213, name: "Munds Park" },
  { rank: 214, name: "Ehrenberg" },
  { rank: 215, name: "Mountainaire" },
  { rank: 216, name: "Kykotsmovi Village" },
  { rank: 217, name: "Teec Nos Pos" },
  { rank: 218, name: "Chilchinbito" },
  { rank: 219, name: "Whitecone" },
  { rank: 220, name: "Sunsites" },
  { rank: 221, name: "Hondah" },
  { rank: 222, name: "Parker Strip" },
  { rank: 223, name: "Mayer" },
  { rank: 224, name: "Seligman" },
  { rank: 225, name: "Komatke" },
  { rank: 226, name: "Bluewater" },
  { rank: 227, name: "Circle City" },
  { rank: 228, name: "Sawmill" },
  { rank: 229, name: "Gadsden" },
  { rank: 230, name: "Patagonia" },
  { rank: 231, name: "Willow Valley" },
  { rank: 232, name: "Upper Santan Village" },
  { rank: 233, name: "Santa Rosa" },
  { rank: 234, name: "Cameron" },
  { rank: 235, name: "Queen Valley" },
  { rank: 236, name: "Houck" },
  { rank: 237, name: "Sonoita" },
  { rank: 238, name: "Brenda" },
  { rank: 239, name: "Roosevelt Estates" },
  { rank: 240, name: "Miracle Valley" },
  { rank: 241, name: "Sanders" },
  { rank: 242, name: "J-Six Ranchettes" },
  { rank: 243, name: "Peeples Valley" },
  { rank: 244, name: "Duncan" },
  { rank: 245, name: "St. Michaels" },
  { rank: 246, name: "Ganado" },
  { rank: 247, name: "Walnut Creek" },
  { rank: 248, name: "Hotevilla-Bacavi" },
  { rank: 249, name: "San Jose" },
  { rank: 250, name: "Low Mountain" },
  { rank: 251, name: "Vicksburg" },
  { rank: 252, name: "Maricopa Colony" },
  { rank: 253, name: "Rancho Mesa Verde" },
  { rank: 254, name: "Cactus Forest" },
  { rank: 255, name: "Many Farms" },
  { rank: 256, name: "Arizona Village" },
  { rank: 257, name: "Tusayan" },
  { rank: 258, name: "Salome" },
  { rank: 259, name: "Yarnell" },
  { rank: 260, name: "Donovan Estates" },
  { rank: 261, name: "Golden Shores" },
  { rank: 262, name: "Round Rock" },
  { rank: 263, name: "Pinedale" },
  { rank: 264, name: "Del Muerto" },
  { rank: 265, name: "Rainbow City" },
  { rank: 266, name: "Tolani Lake" },
  { rank: 267, name: "Dennehotso" },
  { rank: 268, name: "Arivaca Junction" },
  { rank: 269, name: "Hayden" },
  { rank: 270, name: "Tacna" },
  { rank: 271, name: "Round Valley" },
  { rank: 272, name: "Icehouse Canyon" },
  { rank: 273, name: "Gisela" },
  { rank: 274, name: "Mesquite Creek" },
  { rank: 275, name: "Elephant Head" },
  { rank: 276, name: "Burnside" },
  { rank: 277, name: "Arivaca" },
  { rank: 278, name: "Red Mesa" },
  { rank: 279, name: "Solomon" },
  { rank: 280, name: "So-Hi" },
  { rank: 281, name: "Turkey Creek" },
  { rank: 282, name: "Ash Fork" },
  { rank: 283, name: "Nutrioso" },
  { rank: 284, name: "St. Johns" },
  { rank: 285, name: "Topawa" },
  { rank: 286, name: "Nazlini" },
  { rank: 287, name: "Rock Point" },
  { rank: 288, name: "York" },
  { rank: 289, name: "Jerome" },
  { rank: 290, name: "Keams Canyon" },
  { rank: 291, name: "Tees Toh" },
  { rank: 292, name: "Greenehaven" },
  { rank: 293, name: "Steamboat" },
  { rank: 294, name: "Stotonic Village" },
  { rank: 295, name: "Bowie" },
  { rank: 296, name: "La Paz Valley" },
  { rank: 297, name: "Wenden" },
  { rank: 298, name: "Rough Rock" },
  { rank: 299, name: "Stanfield" },
  { rank: 300, name: "Cedar Creek" },
  { rank: 301, name: "Nelson" },
  { rank: 302, name: "Wheatfields" },
  { rank: 303, name: "Dudleyville" },
  { rank: 304, name: "East Fork" },
  { rank: 305, name: "Indian Wells" },
  { rank: 306, name: "El Prado Estates" },
  { rank: 307, name: "Hackberry" },
  { rank: 308, name: "Vernon" },
  { rank: 309, name: "Yuma Proving Ground" },
  { rank: 310, name: "Young" },
  { rank: 311, name: "Bitter Springs" },
  { rank: 312, name: "Sacaton Flats Village" },
  { rank: 313, name: "Lazy Y U" },
  { rank: 314, name: "Pisinemo" },
  { rank: 315, name: "Shonto" },
  { rank: 316, name: "Fort Thomas" },
  { rank: 317, name: "San Miguel" },
  { rank: 318, name: "Central" },
  { rank: 319, name: "Dateland" },
  { rank: 320, name: "Winslow West" },
  { rank: 321, name: "Pinal" },
  { rank: 322, name: "Carrizo" },
  { rank: 323, name: "Goodyear Village" },
  { rank: 324, name: "Oak Creek Canyon" },
  { rank: 325, name: "Wall Lane" },
  { rank: 326, name: "Winkelman" },
  { rank: 327, name: "Chloride" },
  { rank: 328, name: "Aguila" },
  { rank: 329, name: "Palominas" },
  { rank: 330, name: "Kaka" }
]

interface ArizonaCitySelectorProps {
  onCitySelect: (city: City) => void
  selectedCities: string[]
}

const ArizonaCitySelector: React.FC<ArizonaCitySelectorProps> = ({ onCitySelect, selectedCities }) => {
  return (
    <div className="space-y-2">
      <label htmlFor="city-select" className="block text-sm font-medium text-[#E4B649]">
        Select an Arizona City
      </label>
      <Select onValueChange={(value) => {
        const selectedCity = ARIZONA_CITIES.find(city => city.name === value)
        if (selectedCity) onCitySelect(selectedCity)
      }}>
        <SelectTrigger id="city-select" className="w-full bg-black/50 border-[#E4B649]/20 text-white">
          <SelectValue placeholder="Choose a city" />
        </SelectTrigger>
        <SelectContent className="bg-black border-[#E4B649]/20">
          <ScrollArea className="h-[200px]">
            {ARIZONA_CITIES.map((city) => (
              <SelectItem 
                key={city.rank} 
                value={city.name}
                className="text-white hover:bg-[#E4B649]/20"
                disabled={selectedCities.includes(city.name)}
              >
                {city.name}
              </SelectItem>
            ))}
          </ScrollArea>
        </SelectContent>
      </Select>
      <p className="text-xs text-[#E4B649]/70">
        * You can select up to 10 cities from Arizona
      </p>
    </div>
  )
}

export default ArizonaCitySelector

